### ISSUE TITLE
The price along with quantity of item is showing to user even if he/she delete the item from the BuyList.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#1]
![bug-1](https://cloud.githubusercontent.com/assets/11290480/6462361/61fe2ba8-c1ce-11e4-8565-74d69fa607f9.jpg)
Pre-requisite:
1.Download the latest build for "SellMeBooks" application.

Steps to Reproduce:
1.Launch the application in ios device.
2.Add items to the BuyList and then delete those items.
3.Observe that the price and quantity of item is still showing to the user.

Actual Result:
The price along with quantity of item shown to user even if he/she delete the item from the BuyList.

Expected Result:
The price and  quantity of item should not be shown to user even if he/she delete the item from the BuyList.

**Comment by gbawa** [comment]
Fixed. Can be tested in next version 1.1 release.

**Comment by manishabal** [comment]
Regressed and verified that this issue is fixed.
