### ISSUE TITLE
[Android]: Two orders are getting displayed under ‘Buy List’ when user is placing a single order.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#16]
![bug-16](https://cloud.githubusercontent.com/assets/11290480/6502817/f7a83f52-c34c-11e4-9ee7-a6b81108a6ee.jpg)
Steps to Reproduce:
1. Launch the application in android device.
2. Select ‘Keypad’ options and then provide ISBN no.
3. Click on ‘Add ’ to my list option,
4. Observe that under ‘Buy List’ two order are getting displayed.

Actual Result:
Two orders are getting displayed under ‘Buy List’ when user is placing a single order.

Expected Result:
Only single order should be displayed under ‘Buy List’ when user is placing an order.

***Please find the attached screen-shots for references.

Other Occurrences: N/A

**Comment by mohitum007** [comment]
Not an issue. It is part of app functionality.
