### ISSUE TITLE
The date is not getting displayed under 'Date' column for 'Shipment History' when user select 'More' options in "SellMeBooks" application.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#2]
![bug-2](https://cloud.githubusercontent.com/assets/11290480/6462800/7d5c8c10-c1d2-11e4-9e1c-c95d9a929905.jpg)
Pre-requisite:
1.Download the latest build for "SellMeBooks" application.

Steps to Reproduce:
1.Launch the application in ios device.
2.Select 'More' option and then click on "Account History" icon.
3.Under "Account History" icon select 'Shipment History'.
4.Observe that date is not getting displayed under 'Date' column.

Actual Result:
The date is not getting displayed under 'Date' column for 'Shipment History' when user select 'More' options in "SellMeBooks" application.

Expected Result:
The date is not getting displayed under 'Date' column for 'Shipment History' when user select 'More' options in "SellMeBooks" application.

***Please refer the attached screen shots for references

Other Occurrences:
The same issue is reproducible for ‘Material Request History’ when user select 'More' options in "SellMeBooks" application.

**Comment by gbawa** [comment]
This is not valid. You are getting this issue because you are testing with old test account which were adding wrong data while development. To test this properly signup new account and add history from that account and then check history detail.
