### ISSUE TITLE
User is not able to delete the particular item under ‘BuyList’ tab when he/she add multiple items to same.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#20]
![bug-20](https://cloud.githubusercontent.com/assets/11290480/6576082/8390d25c-c75a-11e4-90b5-71ece70bdc9c.png)

Pre-requisite:
Install the latest ipa for ‘SellMeBook’ application.

Steps to reproduce:
1.Launch the application in ios device.
2.Enter valid credentials.
3.Select ‘Keypad’ tab and enter an ISBN code.
4.Get offer by that particular ISBN no. and select ‘Add to my list’.
5.Again add another item of different ISBN no.
6.Observe that user is not able to delete the particular item.

Actual Result:
User is not able to delete the particular item under ‘BuyList’ tab when he/she add multiple items to same.

Expected Result:
User should be able to delete the particular item under ‘BuyList’ tab when he/she add multiple items to the buylist tab.

***Please find the attached screen-shot for references.

Other occurrences: If user try to delete the item then the whole items are deleted from Buylist.

**Comment by gbawa** [comment]
Swiping any row of a list from right to left gives you an option to deletes that particular row.
