### ISSUE TITLE
User is not able to save the item in separate entity when he/she add items from keypad.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#21]
Pre-requisite:
Install the latest ipa for ‘SellMeBook’ application.

Steps to reproduce:
1.Launch the application in ios device.
2.Enter valid credentials.
3.Select ‘Keypad’ tab and enter an ISBN code.
4.Get offer by that particular ISBN no. and select ‘Add to my list’.
5.Again add another item of different ISBN no.
6.Observe that user is not able to parse the particular item.

Actual Result:
User is not able to save the item in separate entity when he/she add items.

Expected Result:
User should be able to save the item in separate entity when he/she add items.

Other occurrences: N/A

**Comment by gbawa** [comment]
This is not a valid point as per the flow of the app.
