### ISSUE TITLE
[iphone5]:The alignment for title text is not correct under ‘Order Details’ while navigating through Order History in ‘SellMeBook’ application.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#22]
![bug-22](https://cloud.githubusercontent.com/assets/11290480/6591212/42ef8e22-c7e2-11e4-9d69-3c2c8249b65c.jpg)
Pre-requisite:
Install the latest ipa for ‘SellMeBook’ application.

Steps to reproduce:
Launch the application in ios device.
Enter valid credentials.
Select ‘More’ tab and then select ‘Account History’ icon.
Now, select ‘Order History’ and choose any order.
Select that particular order to get order detail page.
Observe that the alignment is not correct.

Actual Result:
The alignment for title text is not correct under ‘Order Details’ while navigating through Order History in ‘SellMeBook’ application.

Expected Result:
The alignment for title text should be correct under ‘Order Details’ while navigating through Order History in ‘SellMeBook’ application.

***Please find the attached screen-shot for references.

Other occurrences: The same issue is reproducible for some of the orders in iphone6
![bug-22](https://cloud.githubusercontent.com/assets/11290480/6591215/50005646-c7e2-11e4-8072-3cdf7acb210b.jpg)

**Comment by gbawa** [comment]
Fixed.

**Comment by manishabal** [comment]
Regressed and verified that this issue is fixed.
