### ISSUE TITLE
[BluetoothScanner]:The quantity of item becomes zero when the item is added to 'BuyList' from scanning the barcode using bluetooth scanner

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#24]
[Bluetooth Scanner]:The quantity of item becomes zero when the item is added to 'BuyList' from scanning the barcode using bluetooth scanner

**Comment by gbawa** [comment]
Fixed.

**Comment by manishabal** [comment]
Regressed and verified that this issue is fixed.
