### ISSUE TITLE
The header for ‘Material Request History’ is displaying as ‘Material History’ when user select this under Account History icon for ‘More’ option in "SellMeBooks" application.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#3]
![bug-3](https://cloud.githubusercontent.com/assets/11290480/6462963/f305e316-c1d3-11e4-8f8b-49b3727cbdd5.jpg)
Pre-requisite:
1.Download the latest build for "SellMeBooks" application.

Steps to Reproduce:
1.Launch the application in ios device.
2.Select 'More' option and then click on "Account History" icon.
3.Click on ‘Material Request History’ .
4.Observe the header displaying is as ‘Material History’

Actual Result:
The header for ‘Material Request History’ is displaying as ‘Material History’ when user select this under Account History icon for ‘More’ option in "SellMeBooks" application.

Expected Result:
There should be consistency between the header under ‘Account History’ icon for ‘More’ option in "SellMeBooks" application.

***Please refer the attached screen shots for references

Other Occurrences: N/A

**Comment by gbawa** [comment]
Fixed. Can be tested in next release 1.1

**Comment by manishabal** [comment]
The same issue is reproducible for ‘Material' icon when user select 'More' options in "SellMeBooks" application.

**Comment by gbawa** [comment]
This issue has been fixed for version 1.1.

**Comment by manishabal** [comment]
Regressed and verified that this issue is fixed now
