### ISSUE TITLE
The ‘Submit’ button remains disable after entering the values for ‘Material Request’ for ‘More’ options option in "SellMeBooks" application.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#4]
![bug-4](https://cloud.githubusercontent.com/assets/11290480/6463580/7a41ea5a-c1d9-11e4-8d9b-f50e4ca2588c.jpg)
Pre-requisite:
1.Download the latest build for "SellMeBooks" application.

Steps to Reproduce:
1.Launch the application in ios device.
2.Select 'More' option and then select ‘Material’.
3.Select check boxes and provide value.
4.Observe that ‘Submit’ button remains disable.

Actual Result:
The ‘Submit’ button remains disable after entering the values for ‘Material Request’ for ‘More’ options option in "SellMeBooks" application.

Expected Result:
The ‘Submit’ button should be enable after entering the values for ‘Material Request’ for ‘More’ options option in "SellMeBooks" application.

***Please refer the attached screen shots for references

Other Occurrences: N/A

**Comment by gbawa** [comment]
This issue has been fixed for version 1.1.

**Comment by manishabal** [comment]
Regressed and verified that this issue is fixed
