### ISSUE TITLE
The sorting is not correct under ‘User Name’ column for “Order History” in “SellMeBooks” application.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#5]
![bug-5](https://cloud.githubusercontent.com/assets/11290480/6479108/b2452e30-c265-11e4-84a0-8732d43afc80.jpg)
Note:
Use the URL “http://sellmebooks.trantorinc.com/” with credentials ‘admin/admin’.

Steps to Reproduce:
1.Login to admin panel with valid credentials.
2.Click on Order History icon.
3.Click on ‘User Name’ column for sorting purpose.
4.Observe that sorting is not correct.

Actual Result:
The sorting is not correct under ‘User Name’ column for “Order History” in “SellMeBooks” application.

Expected Result:
The sorting should be correct under ‘User Name’ column for “Order History” in “SellMeBooks” application.

***Please find the attached screen shots for references.

Other occurrences:
The same issue is reproducible for ‘School Name’ column in Order History icon  in “SellMeBooks” application.

**Comment by webmasterphp** [comment]
I have removed the sorting for the user name. Sorting by user name is not required there.

**Comment by manishabal** [comment]
Verified that this issue is fixed now.
