### ISSUE TITLE
The header title is displaying as ‘Manage Pins’ when user click on ‘‘Manage User Pin’ icon in admin panel of "SellMeBooks" application.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#6]
![bug-6](https://cloud.githubusercontent.com/assets/11290480/6479374/54dcc35c-c26a-11e4-86c0-0de43c691f91.jpg)
Note:
Use the URL “http://sellmebooks.trantorinc.com/” with credentials ‘admin/admin’.

Steps to Reproduce:
1.Login to admin panel using valid credentials.
2.Click on ‘Manage User Pin’ icon.
3. Observe that the header name is as ‘Manage Pin’.

Actual Result:
The header title is displaying as ‘Manage Pins’ when user click on ‘‘Manage User Pin’ icon in admin panel of "SellMeBooks" application.

Expected Result:
There should be consistency between the two header names.

***Please refer the attached screen shots for references

Other Occurrences: N/A

**Comment by webmasterphp** [comment]
It's not a part of phase 2. Please close it. FYI, don't do testing for the "Manage User Pin" and "Manage Books" tab.

**Comment by manishabal** [comment]
As per the updates from dev team, QA team is closing this issue.
