### ISSUE TITLE
‘Search by order id’ text is showing in the Search text field although there is no order id column under ‘Order History’.

### ISSUE THREAD

**Issue by manishabal** [parveshjagga1/SellMeBooks#7]
![bug-7](https://cloud.githubusercontent.com/assets/11290480/6482423/beb71b08-c28b-11e4-8a73-2db92170ed4e.jpg)
Note:
Use the URL “http://sellmebooks.trantorinc.com/” with credentials ‘admin/admin’.

Steps to Reproduce:
1.Login to admin panel using valid credentials.
2.Click on ‘Order History’ icon.
3. Observe that ‘Search by order id’ text is showing in the Search text field.

Actual Result: ‘Search by order id’ text is showing in the Search text field although there is no order id column under ‘Order History’.

Expected Result:
‘Search by ---’ text should be shown to user under ‘Order History’.

***Please refer the attached screen shots for references

Other Occurrences: N/A

**Comment by webmasterphp** [comment]
It's  fixed.
